spring.application.name=spring-ai
spring.main.web-application-type=none

spring.config.import=optional:file:.env[.properties]
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4.1-nano
spring.ai.model.chat=openai
spring.ai.model.embedding=openai
spring.ai.mcp.server.enabled=false